name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions: {} #reset

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Changesets
        run: echo ${{steps.changesets.outputs}}
      - name: Check if branch name is 'changeset-release/main'
        run: |
          echo "${GITHUB_REF##refs/heads/}"
          if [[ "${GITHUB_REF##refs/heads/}" == "changeset-release/main" ]]; then
            echo "Branch name is 'changeset-release/main'"
            BRANCH_IS_RELEASE=true
          else
            echo "Branch name is not 'changeset-release/main'"
            BRANCH_IS_RELEASE=false
          fi
      - name: Build Static Files
        if: ${{ steps.check-branch-name.outputs.BRANCH_IS_RELEASE == 'true' }}
        run: npm run build
      - name: Upload Artifact
        if: ${{ steps.check-branch-name.outputs.BRANCH_IS_RELEASE == 'true' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        if: ${{ steps.check-branch-name.outputs.BRANCH_IS_RELEASE == 'true' }}
        id: deployment
        uses: actions/deploy-pages@v2
